FROM alpine:3.9
LABEL maintainer="devops@radixdlt.com"
USER root


# add jdk
RUN apk add --no-cache openjdk8

# add distTar
ADD build/distributions/faucet-service-*.tar /opt

# permissions
RUN mv /opt/faucet-service-* /opt/faucet-service && \
    mkdir /opt/faucet-service/etc && \
    chown -R nobody:nogroup /opt/faucet-service

# volumize
VOLUME /opt/faucet-service/etc

# workdir
WORKDIR /opt/faucet-service

# entrypoint
ENTRYPOINT ["./bin/faucet-service"]

USER nobody:nogroup
